;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				backward-delete-char
				backward-sentence
				backward-sexp
				beginning-of-buffer
				beginning-of-defun
				c-electric-semi&comma
				downcase-region
				electric-newline-and-maybe-indent
				end-of-buffer
				forward-sexp
				gdscript-indent-dedent-line-backspace
				indent-relative
				kill-region
				prelude-move-beginning-of-line
				save-some-buffers
				tabber
				typescript-insert-and-autoconvert-to-template
				typescript-insert-and-indent
				upcase-region
				))

(setq mc/cmds-to-run-once
      '(
				battery
				eval-print-last-sexp
				helm-M-x
				helm-gtags-select
				shrink-window-horizontally
				xref-pop-marker-stack
				))
