;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-delete-char
        backward-sentence
        backward-sexp
        beginning-of-buffer
        beginning-of-defun
        c-electric-semi&comma
        comment-or-uncomment-region
        downcase-region
        electric-newline-and-maybe-indent
        end-of-buffer
        forward-sexp
        gdscript-indent-dedent-line-backspace
        helm-find-files
        iedit-mode
        ignore
        indent-relative
        indent-rigidly
        indent-rigidly-left
        indent-rigidly-right
        kill-region
        nxml-electric-slash
        prelude-move-beginning-of-line
        save-some-buffers
        tabber
        typescript-insert-and-autoconvert-to-template
        typescript-insert-and-indent
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        battery
        count-lines-page
        delete-window
        elscreen-create
        elscreen-jump
        elscreen-next
        elscreen-previous
        eval-print-last-sexp
        handle-switch-frame
        helm-M-x
        helm-confirm-and-exit-minibuffer
        helm-gtags-select
        helm-ls-git-ls
        lsp-ui-doc--handle-mouse-movement
        lsp-ui-doc-focus-frame
        mouse-appearance-menu
        mouse-set-region
        overwrite-mode
        previous-buffer
        shrink-window-horizontally
        xref-pop-marker-stack
        ))
